In [1]:
# Create a vector
import numpy as np
vector = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
EPSILON = 0.1

In [2]:
print(vector)
print(vector.T)
print(vector.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
(2, 5)


In [3]:
print(np.linalg.norm(vector, aix

SyntaxError: incomplete input (672960552.py, line 1)

In [ ]:
print((vector.T / (np.linalg.norm(vector.T, axis=0) + EPSILON)).T)
print(vector / (np.linalg.norm(vector, axis=0) + EPSILON))

In [ ]:
print(np.mean(vector, axis=0))
print(np.mean(vector))
print(np.mean(vector, axis=1))
print(vector)

In [ ]:
print(np.linalg.norm(vector.T, axis=1))

In [4]:
print(sqrt(5))

NameError: name 'sqrt' is not defined

In [5]:
from math import sqrt
print(sqrt(1 + 4 + 9 + 16 + 25))

7.416198487095663


In [6]:
vector = [[[1, 2], [1, 2], [1, 3]],
     [[2, 3], [2, 3], [3, 4]]]

In [7]:
print(a)

NameError: name 'a' is not defined

In [8]:
a[0][0][0], a[1][0][0]
a[0][0][1], a[1][0][1]

NameError: name 'a' is not defined

In [9]:
class_mean = np.mean(vector, axis=0)
print(class_mean)

[[1.5 2.5]
 [1.5 2.5]
 [2.  3.5]]


In [10]:
Mu_P = 0
print(np.sum((class_mean - Mu_P) ** 2, axis=1))

[ 8.5   8.5  16.25]


In [11]:
(class_mean - Mu_P) ** 2

array([[ 2.25,  6.25],
       [ 2.25,  6.25],
       [ 4.  , 12.25]])

In [12]:
print(np.argmin([5, 1, 2, 3, 4]))

1
