In [16]:
# Create a vector
data = np.random.rand(1000, 64)
import numpy as np
vectors = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
vectors = np.random.rand(1000, 64)
EPSILON = 0.1
print((vector.T / (np.linalg.norm(vector.T, axis=0) + EPSILON)).T)
m = 100
class_mean = np.mean(vectors, axis=0)


print(class_mean)

[[0.09685925 0.07909643 0.1948896  ... 0.05514409 0.15274036 0.05978436]
 [0.07100212 0.08483002 0.14226438 ... 0.02595736 0.13500185 0.15577939]
 [0.11270325 0.12375291 0.15599901 ... 0.1954221  0.21673299 0.11130564]
 ...
 [0.11225814 0.06502016 0.06637805 ... 0.20953829 0.02300091 0.09898459]
 [0.06046909 0.178539   0.13816568 ... 0.17772681 0.04686039 0.03997699]
 [0.11702067 0.18555473 0.09075857 ... 0.03696871 0.09614097 0.12914416]]
[0.51103822 0.49765367 0.50679676 0.48454722 0.50897643 0.50685621
 0.50369895 0.50882555 0.48668352 0.4878985  0.49298123 0.49263153
 0.51099444 0.49372701 0.49489706 0.49357315 0.49831027 0.50726454
 0.49526819 0.5013773  0.49638684 0.4967407  0.50418502 0.49964039
 0.49583617 0.49112401 0.48808059 0.51497486 0.49017909 0.50525893
 0.49407252 0.49765245 0.50958954 0.48644451 0.50183674 0.50924742
 0.50335254 0.50702181 0.50665693 0.49589759 0.4841946  0.50172108
 0.50649112 0.51074779 0.49809629 0.50226899 0.50738059 0.50614809
 0.51046229 0.497313

In [17]:
# Select
selected_exemplars = []
exemplar_vectors = []
for k in range(1, m + 1):
    print(k)
    S = np.sum(exemplar_vectors, axis=0)  # [feature_dim] sum of selected exemplars vectors
    mu_p = (vectors + S) / k  # [n, feature_dim] sum to all vectors
    i = np.argmin(np.sqrt(np.sum((class_mean - mu_p) ** 2, axis=1)))

    selected_exemplars.append(np.array(data[i]))  # new object to avoid passing by inference
    exemplar_vectors.append(np.array(vectors[i]))  # new object to avoid passing by inference
    vectors = np.delete(vectors, i, axis=0)  # Remove it to avoid duplicative selection
    data = np.delete(data, i, axis=0)  # Remove it to avoid duplicative selection
selected_exemplars = np.array(selected_exemplars)
# exemplar_targets = np.full(m, class_idx)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [ ]:
print(np.linalg.norm(vector.T, axis=1))

In [4]:
print(sqrt(5))

NameError: name 'sqrt' is not defined

In [5]:
from math import sqrt
print(sqrt(1 + 4 + 9 + 16 + 25))

7.416198487095663


In [6]:
vector = [[[1, 2], [1, 2], [1, 3]],
     [[2, 3], [2, 3], [3, 4]]]

In [7]:
print(a)

NameError: name 'a' is not defined

In [8]:
a[0][0][0], a[1][0][0]
a[0][0][1], a[1][0][1]

NameError: name 'a' is not defined

In [9]:
class_mean = np.mean(vector, axis=0)
print(class_mean)

[[1.5 2.5]
 [1.5 2.5]
 [2.  3.5]]


In [10]:
Mu_P = 0
print(np.sum((class_mean - Mu_P) ** 2, axis=1))

[ 8.5   8.5  16.25]


In [11]:
(class_mean - Mu_P) ** 2

array([[ 2.25,  6.25],
       [ 2.25,  6.25],
       [ 4.  , 12.25]])

In [12]:
print(np.argmin([5, 1, 2, 3, 4]))

1
