In [26]:
# Create a vector
import numpy as np
vector = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
EPSILON = 0.1

In [55]:
print(vector)
print(vector.T)
print(vector.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
(2, 5)


In [64]:
print(np.linalg.norm(vector, aix

[7.41619849 9.48683298]


In [48]:
print((vector.T / (np.linalg.norm(vector.T, axis=0) + EPSILON)).T)
print(vector / (np.linalg.norm(vector, axis=0) + EPSILON))

[[0.13304598 0.26609196 0.39913794 0.53218392 0.6652299 ]
 [0.20861947 0.3129292  0.41723894 0.52154867 0.62585841]]
[2.23606798 3.60555128 5.         6.40312424 7.81024968]
[[0.42806973 0.53973076 0.58823529 0.61508897 0.6320913 ]
 [0.85613947 0.80959614 0.78431373 0.76886121 0.75850956]]


In [58]:
print(np.mean(vector, axis=0))
print(np.mean(vector))
print(np.mean(vector, axis=1))
print(vector)

[1.5 2.5 3.5 4.5 5.5]
3.5
[3. 4.]
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [9]:
print(np.linalg.norm(vector.T, axis=1))

[2.23606798 3.60555128 5.         6.40312424 7.81024968]


In [10]:
print(sqrt(5))

NameError: name 'sqrt' is not defined

In [13]:
from math import sqrt
print(sqrt(1 + 4 + 9 + 16 + 25))

7.416198487095663


In [79]:
vector = [[[1, 2], [1, 2], [1, 3]],
     [[2, 3], [2, 3], [3, 4]]]

In [80]:
print(a)

[[[1, 2], [1, 2], [1, 3]], [[2, 3], [2, 3], [3, 4]]]


In [90]:
a[0][0][0], a[1][0][0]
a[0][0][1], a[1][0][1]

(2, 3)

In [91]:
class_mean = np.mean(vector, axis=0)
print(class_mean)

[[1.5 2.5]
 [1.5 2.5]
 [2.  3.5]]


In [93]:
Mu_P = 0
print(np.sum((class_mean - Mu_P) ** 2, axis=1))

[ 8.5   8.5  16.25]


In [94]:
(class_mean - Mu_P) ** 2

array([[ 2.25,  6.25],
       [ 2.25,  6.25],
       [ 4.  , 12.25]])

In [99]:
print(np.argmin([5, 1, 2, 3, 4]))

1
