In [1]:
kdd_finetune = [100, 97.4, 55.75, 34.89, 79.1, 78.89]
kdd_der = [100, 99.97, 99.96, 99.85, 99.83, 99.83]
kdd_memo = [100, 99.78, 99.67, 98.16, 99.23, 99.4]

In [4]:
# Testing cross entropy
import torch
from torch.nn import functional as F
from torch.nn import LogSoftmax
from torch import nn

In [5]:
input = torch.randn(3, 5, requires_grad=True)
print(input)
target = torch.randint(5, (3,), dtype=torch.int64)
loss = F.cross_entropy(input, target)
print(loss)
print(type(loss))
print(loss.backward())
loss = nn.NLLLoss()
m = LogSoftmax(dim=1)
print(m(input))
print(target)
print(loss(m(input), target))

tensor([[ 1.1362,  0.1501,  0.0812,  0.0934, -0.7428],
        [ 0.2865, -0.4536,  0.2225, -0.8563,  0.3789],
        [-0.4626,  0.5787, -0.7395, -1.0337, -0.6823]], requires_grad=True)
tensor(1.7304, grad_fn=<NllLossBackward0>)
<class 'torch.Tensor'>
None
tensor([[-0.8004, -1.7865, -1.8554, -1.8432, -2.6794],
        [-1.3431, -2.0832, -1.4071, -2.4858, -1.2507],
        [-1.7849, -0.7435, -2.0618, -2.3560, -2.0045]],
       grad_fn=<LogSoftmaxBackward0>)
tensor([1, 0, 2])
tensor(1.7304, grad_fn=<NllLossBackward0>)


In [6]:
print((-2.0121 + -3.0772 + -2.6653) / 3) 

-2.5848666666666666


In [7]:
x = torch.tensor([[10000, -100000, 535343, 0, 0], [0, 0, 500, 0, 0], [0, 0, 500, 0, 0]], dtype=torch.float64)
y = torch.tensor([0, 2, 2])
print(y)
print(F.cross_entropy(x, y))

tensor([0, 2, 2])
tensor(175114.3333, dtype=torch.float64)


In [8]:
print(m(input))

tensor([[-0.8004, -1.7865, -1.8554, -1.8432, -2.6794],
        [-1.3431, -2.0832, -1.4071, -2.4858, -1.2507],
        [-1.7849, -0.7435, -2.0618, -2.3560, -2.0045]],
       grad_fn=<LogSoftmaxBackward0>)


In [9]:
m = torch.nn.Softmax(dim=1)

In [10]:
print(torch.log(m(input)))

tensor([[-0.8004, -1.7865, -1.8554, -1.8432, -2.6794],
        [-1.3431, -2.0832, -1.4071, -2.4858, -1.2507],
        [-1.7849, -0.7435, -2.0618, -2.3560, -2.0045]], grad_fn=<LogBackward0>)


In [22]:
random_input_1 = torch.Tensor([[1, 2, 3], [2, 3, 4]])
print(random_input_1)
print(random_input_1.shape)
random_input_2 = torch.Tensor([[1, 2, 3], [2, 3, 5]])
print(random_input_2)
print(random_input_2.shape)
mul = torch.mul(random_input_1, random_input_2)
print(mul)

tensor([[1., 2., 3.],
        [2., 3., 4.]])
torch.Size([2, 3])
tensor([[1., 2., 3.],
        [2., 3., 5.]])
torch.Size([2, 3])
tensor([[ 1.,  4.,  9.],
        [ 4.,  9., 20.]])


In [ ]:
input = torch.randn(64, 10, requires_grad=True)

In [ ]:
input[:, 5:]


In [ ]:
input